stages:
  - production-deployment

Deploy to Production:
  stage: production-deployment
  image: alpine:latest
  script:
    - echo "installing ssh command."
    - apk add --no-cache openssh-client
    - chmod 400 $AWS_PEM_KEY
    - echo "connecting to ssh"
    - ssh -tt -o StrictHostKeyChecking=no -i $AWS_PEM_KEY ec2-user@ec2-13-251-145-122.ap-southeast-1.compute.amazonaws.com /home/ec2-user/beiautoparts.com/deploy-api.sh
    - echo "deployed"
